sudo: false
language: ruby
cache: bundler
before_install:
- gem update --system 2.6.11
- gem install bundler -v 1.12.0
- gem --version

before_script:
- bundle list | grep 'bugsnag\|capistrano'
script: bundle exec rake spec

jobs:
  include:
  # JRuby 1.9
  - stage: test
    env: CAP_2_TEST=true
    install: bundle _1.12.0_ install --with test bugsnag
    rvm: jruby-19mode
  - stage: test
    env: CAP_2_TEST=true
    install: bundle _1.12.0_ install --with test --without bugsnag
    rvm: jruby-19mode
  - stage: test
    install: bundle _1.12.0_ install --with test bugsnag
    rvm: jruby-19mode
  - stage: test
    install: bundle _1.12.0_ install --with test --without bugsnag
    rvm: jruby-19mode

  # Ruby 2.0.0
  - stage: test
    env: CAP_2_TEST=true
    install: bundle install --with test bugsnag --binstubs
    rvm: 2.0.0
  - stage: test
    env: CAP_2_TEST=true
    install: bundle install --with test --without bugsnag --binstubs
    rvm: 2.0.0
  - stage: test
    install: bundle install --with test bugsnag --binstubs
    rvm: 2.0.0
  - stage: test
    install: bundle install --with test --without bugsnag --binstubs
    rvm: 2.0.0

  # Ruby 2.1.10
  - stage: test
    env: CAP_2_TEST=true
    install: bundle install --with test bugsnag --binstubs
    rvm: 2.1.10
  - stage: test
    env: CAP_2_TEST=true
    install: bundle install --with test --without bugsnag --binstubs
    rvm: 2.1.10
  - stage: test
    install: bundle install --with test bugsnag --binstubs
    rvm: 2.1.10
  - stage: test
    install: bundle install --with test --without bugsnag --binstubs
    rvm: 2.1.10

  # Ruby 2.3.0
  - stage: test
    install: bundle install --with test bugsnag --binstubs
    rvm: 2.3.0
  - stage: test
    install: bundle install --with test --without bugsnag --binstubs
    rvm: 2.3.0

  # Ruby 2.4.2
  - stage: test
    install: bundle install --with test bugsnag --binstubs
    rvm: 2.4.2
  - stage: test
    install: bundle install --with test --without bugsnag --binstubs
    rvm: 2.4.2
