# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"
require "capistrano/scm/git"
require "pp"
install_plugin Capistrano::SCM::Git

# Load bugsnag
require 'bugsnag-capistrano'

set :bugsnag_api_key, ENV['BUGSNAG_API_KEY'] || 'YOUR_API_KEY'
set :bugsnag_endpoint, ENV['BUGSNAG_ENDPOINT']
set :bugsnag_env, ENV["BUGSNAG_RELEASE_STAGE"] || 'production'
set :current_revision, ENV["BUGSNAG_REVISION"]
set :repo_url, ENV["BUGSNAG_REPOSITORY"]
set :app_version, ENV["BUGSNAG_APP_VERSION"]